//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestSoap.JavaSoapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.howtodoinjava.com/xml/school", ConfigurationName="JavaSoapService.StudentDetailsPort")]
    public interface StudentDetailsPort {
        
        // CODEGEN: Generating message contract since the operation StudentDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MyTestSoap.JavaSoapService.StudentDetailsResponse1 StudentDetails(MyTestSoap.JavaSoapService.StudentDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MyTestSoap.JavaSoapService.StudentDetailsResponse1> StudentDetailsAsync(MyTestSoap.JavaSoapService.StudentDetailsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.howtodoinjava.com/xml/school")]
    public partial class StudentDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.howtodoinjava.com/xml/school")]
    public partial class Student : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int standardField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.howtodoinjava.com/xml/school")]
    public partial class StudentDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Student studentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Student Student {
            get {
                return this.studentField;
            }
            set {
                this.studentField = value;
                this.RaisePropertyChanged("Student");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentDetailsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.howtodoinjava.com/xml/school", Order=0)]
        public MyTestSoap.JavaSoapService.StudentDetailsRequest StudentDetailsRequest;
        
        public StudentDetailsRequest1() {
        }
        
        public StudentDetailsRequest1(MyTestSoap.JavaSoapService.StudentDetailsRequest StudentDetailsRequest) {
            this.StudentDetailsRequest = StudentDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.howtodoinjava.com/xml/school", Order=0)]
        public MyTestSoap.JavaSoapService.StudentDetailsResponse StudentDetailsResponse;
        
        public StudentDetailsResponse1() {
        }
        
        public StudentDetailsResponse1(MyTestSoap.JavaSoapService.StudentDetailsResponse StudentDetailsResponse) {
            this.StudentDetailsResponse = StudentDetailsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentDetailsPortChannel : MyTestSoap.JavaSoapService.StudentDetailsPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentDetailsPortClient : System.ServiceModel.ClientBase<MyTestSoap.JavaSoapService.StudentDetailsPort>, MyTestSoap.JavaSoapService.StudentDetailsPort {
        
        public StudentDetailsPortClient() {
        }
        
        public StudentDetailsPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentDetailsPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentDetailsPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentDetailsPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyTestSoap.JavaSoapService.StudentDetailsResponse1 MyTestSoap.JavaSoapService.StudentDetailsPort.StudentDetails(MyTestSoap.JavaSoapService.StudentDetailsRequest1 request) {
            return base.Channel.StudentDetails(request);
        }
        
        public MyTestSoap.JavaSoapService.StudentDetailsResponse StudentDetails(MyTestSoap.JavaSoapService.StudentDetailsRequest StudentDetailsRequest) {
            MyTestSoap.JavaSoapService.StudentDetailsRequest1 inValue = new MyTestSoap.JavaSoapService.StudentDetailsRequest1();
            inValue.StudentDetailsRequest = StudentDetailsRequest;
            MyTestSoap.JavaSoapService.StudentDetailsResponse1 retVal = ((MyTestSoap.JavaSoapService.StudentDetailsPort)(this)).StudentDetails(inValue);
            return retVal.StudentDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyTestSoap.JavaSoapService.StudentDetailsResponse1> MyTestSoap.JavaSoapService.StudentDetailsPort.StudentDetailsAsync(MyTestSoap.JavaSoapService.StudentDetailsRequest1 request) {
            return base.Channel.StudentDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyTestSoap.JavaSoapService.StudentDetailsResponse1> StudentDetailsAsync(MyTestSoap.JavaSoapService.StudentDetailsRequest StudentDetailsRequest) {
            MyTestSoap.JavaSoapService.StudentDetailsRequest1 inValue = new MyTestSoap.JavaSoapService.StudentDetailsRequest1();
            inValue.StudentDetailsRequest = StudentDetailsRequest;
            return ((MyTestSoap.JavaSoapService.StudentDetailsPort)(this)).StudentDetailsAsync(inValue);
        }
    }
}
